### ISSUE TITLE
maven上的0.0.5版是不是有問題？

### ISSUE THREAD

**Issue by abccbaandy** [program-in-chinese/zhconverter#4]
build錯誤
`Cannot resolve com.github.program_in_chinese:junit4_in_chinese:0.0.1-SNAPSHOT`

**Comment by makewheels** [comment]
<dependency>
            <groupId>com.github.nobodxbodon</groupId>
            <artifactId>zhconverter</artifactId>
            <version>0.0.5</version>
            <exclusions>
                <exclusion>
                    <groupId>com.github.program_in_chinese</groupId>
                    <artifactId>junit4_in_chinese</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

**Comment by makewheels** [comment]
`<dependency>
            <groupId>com.github.nobodxbodon</groupId>
            <artifactId>zhconverter</artifactId>
            <version>0.0.5</version>
            <exclusions>
                <exclusion>
                    <groupId>com.github.program_in_chinese</groupId>
                    <artifactId>junit4_in_chinese</artifactId>
                </exclusion>
            </exclusions>
        </dependency>`

**Comment by makewheels** [comment]
<dependency>
            <groupId>com.github.nobodxbodon</groupId>
            <artifactId>zhconverter</artifactId>
            <version>0.0.5</version>
            <exclusions>
                <exclusion>
                    <groupId>com.github.program_in_chinese</groupId>
                    <artifactId>junit4_in_chinese</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

**Comment by makewheels** [comment]
`<dependency>
    <groupId>com.github.nobodxbodon</groupId>
    <artifactId>zhconverter</artifactId>
    <version>0.0.5</version>
    <exclusions>
        <exclusion>
            <groupId>com.github.program_in_chinese</groupId>
            <artifactId>junit4_in_chinese</artifactId>
        </exclusion>
    </exclusions>
</dependency>`

**Comment by makewheels** [comment]
![image](https://user-images.githubusercontent.com/33256842/104086057-65ffdc80-528f-11eb-91d2-4347b986e780.png)

**Comment by makewheels** [comment]
0.0.1没有snapshot
<dependency>
	  <groupId>com.github.program_in_chinese</groupId>
	  <artifactId>junit4_in_chinese</artifactId>
	  <version>0.0.1</version>
	</dependency>

**Comment by makewheels** [comment]
<dec>

**Comment by makewheels** [comment]
依赖里面，version，0.0.1没有snapshot
\<dependency\>
  \<groupId\>com.github.program_in_chinese\</groupId\>
  \<artifactId\>junit4_in_chinese\</artifactId\>
  \<version\>0.0.1\</version\>
\</dependency\>

\<dependency\>
    \<groupId\>com.github.nobodxbodon\</groupId\>
    \<artifactId\>zhconverter\</artifactId\>
    \<version\>0.0.5\</version\>
    \<exclusions\>
	\<exclusion\>
	    \<groupId\>com.github.program_in_chinese\</groupId\>
	    \<artifactId\>junit4_in_chinese\</artifactId\>
	\</exclusion\>
    \</exclusions\>
\</dependency\>

**Comment by makewheels** [comment]
依赖里面，version，0.0.1没有snapshot
\<dependency\>
&nbsp;&nbsp;\<groupId\>com.github.program_in_chinese\</groupId\>
&nbsp;&nbsp;\<artifactId\>junit4_in_chinese\</artifactId\>
&nbsp;&nbsp;\<version\>0.0.1\</version\>
\</dependency\>

\<dependency\>
&nbsp;&nbsp;&nbsp;&nbsp;\<groupId\>com.github.nobodxbodon\</groupId\>
&nbsp;&nbsp;&nbsp;&nbsp;\<artifactId\>zhconverter\</artifactId\>
&nbsp;&nbsp;&nbsp;&nbsp;\<version\>0.0.5\</version\>
&nbsp;&nbsp;&nbsp;&nbsp;\<exclusions\>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\<exclusion\>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\<groupId\>com.github.program_in_chinese\</groupId\>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\<artifactId\>junit4_in_chinese\</artifactId\>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\</exclusion\>
&nbsp;&nbsp;&nbsp;&nbsp;\</exclusions\>
\</dependency\>

**Comment by nobodxbodon** [comment]
@makewheels 感谢解答。
